on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: # Enables on-demand/manual triggering
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3
      - run: |
          pip install -q feedparser praw
          for i in {1..100}; do python auto-post.py; done
        env:
          SECRET: ${{ secrets.SECRET }}
          PASS: ${{ secrets.PASS }}
          USER: ${{ secrets.USER }}
          ID: ${{ secrets.ID }}
