on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: # Enables on-demand/manual triggering
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          pip install -q feedparser praw
          for i in {1..100}; do python auto-post.py; done
        env:
          SECRET: ${{ secrets.SECRET }}
          PASS: ${{ secrets.PASS }}
          USER: ${{ secrets.USER }}
          ID: ${{ secrets.ID }}
          SECRET2: ${{ secrets.SECRET2 }}
          PASS2: ${{ secrets.PASS2 }}
          USER2: ${{ secrets.USER2 }}
          ID2: ${{ secrets.ID2 }}
